name: tracker
description: A health tracking Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: 0.11.2
  cloud_firestore: 6.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^6.1.2
  firebase_core: 4.2.1
  firebase_database: ^12.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.3
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  http_parser: ^4.0.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  pdf: ^3.13.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.0
  printing: ^5.15.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/him.png"
flutter:
  uses-material-design: true
